import type { ArchaeologyBrief } from "@/lib/api";
import { displayBriefQuestionText } from "@/lib/brief-question-text";

function sanitizeFilename(name: string): string {
  return name.replace(/[^\w.-]+/g, "-").replace(/-+/g, "-").slice(0, 80);
}

export function buildBriefMarkdown(
  brief: ArchaeologyBrief,
  expertLabel: string,
  moduleLabel: string,
): string {
  const lines = [
    `# Archaeology Brief`,
    ``,
    `- **Expert:** ${expertLabel}`,
    `- **Module:** ${moduleLabel}`,
    `- **Status:** ${brief.status}`,
    ``,
    `## Questions`,
    ``,
  ];

  for (const q of brief.questions) {
    lines.push(`${q.rank}. ${displayBriefQuestionText(q.question_text)}`);
    lines.push(``);
  }

  lines.push(`---`, `Generated by Backstory — expert-only questions tied to indexed signals.`);
  return lines.join("\n");
}

export function downloadBriefMarkdown(
  brief: ArchaeologyBrief,
  expertLabel: string,
  moduleLabel: string,
): void {
  const body = buildBriefMarkdown(brief, expertLabel, moduleLabel);
  const blob = new Blob([body], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = `${sanitizeFilename(moduleLabel || "archaeology-brief")}.md`;
  anchor.click();
  URL.revokeObjectURL(url);
}
